const appJson = require('./app.json');
require('dotenv').config();

module.exports = () => ({
  ...appJson.expo,
  extra: {
    EXPO_PUBLIC_SUPABASE_URL: process.env.EXPO_PUBLIC_SUPABASE_URL || '',
    EXPO_PUBLIC_SUPABASE_ANON_KEY: process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY || '',
    // BunnyCDN Configuration
    EXPO_PUBLIC_BUNNY_API_KEY: process.env.EXPO_PUBLIC_BUNNY_API_KEY,
    EXPO_PUBLIC_BUNNY_LIBRARY_ID_REELS: process.env.EXPO_PUBLIC_BUNNY_LIBRARY_ID_REELS,
    EXPO_PUBLIC_BUNNY_HOST_REELS: process.env.EXPO_PUBLIC_BUNNY_HOST_REELS,
    EXPO_PUBLIC_BUNNY_LIBRARY_ID_VIDEO: process.env.EXPO_PUBLIC_BUNNY_LIBRARY_ID_VIDEO,
    EXPO_PUBLIC_BUNNY_HOST_VIDEO: process.env.EXPO_PUBLIC_BUNNY_HOST_VIDEO,
    EXPO_PUBLIC_BUNNY_LIBRARY_ID_LIVE: process.env.EXPO_PUBLIC_BUNNY_LIBRARY_ID_LIVE,
    EXPO_PUBLIC_BUNNY_HOST_LIVE: process.env.EXPO_PUBLIC_BUNNY_HOST_LIVE,
    EXPO_PUBLIC_BUNNY_LIBRARY_ID_STORY: process.env.EXPO_PUBLIC_BUNNY_LIBRARY_ID_STORY,
    EXPO_PUBLIC_BUNNY_HOST_STORY: process.env.EXPO_PUBLIC_BUNNY_HOST_STORY,
    EXPO_PUBLIC_BUNNY_STORAGE_ZONE: process.env.EXPO_PUBLIC_BUNNY_STORAGE_ZONE,
    EXPO_PUBLIC_BUNNY_STORAGE_HOST: process.env.EXPO_PUBLIC_BUNNY_STORAGE_HOST,
  },
});


